version: '3.8'
services:
  recording:
    build:
      context: .
      dockerfile: Recording.Dockerfile
    volumes:
      - recordings:/app/recordings
    devices:
      - /dev/snd:/dev/snd
    environment:
      - RECORDING_LENGTH=15
      - SAMPLE_RATE=48000
      - FILENAME_FORMAT={date}-birdnet-{time}.wav
      - RECS_DIR=/app/recordings
      - MAX_RECORDS=1  # Keep only 10 latest recordings
  analyzer:
    build:
      context: .
      dockerfile: Analyze.Dockerfile
    volumes:
      - recordings:/app/recordings
      - processed:/app/processed
    environment:
      - LATITUDE=0.0  # Set default value
      - LONGITUDE=0.0 # Set default value
      - SENSITIVITY=1.0
      - OVERLAP=0.0
      - MIN_CONF=0.1
      - SHOW_LEVELS=false
    depends_on:
      - recording

  server:
    hostname: server
    build:
      context: .
      dockerfile: Server.Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - db-data:/app/database  # Database storage  
      - recordings:/app/recordings:ro  # Add access to recordings
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5050"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  recordings:
  processed:  
  db-data: