version: '3.8'
services:
  recording:
    build:
      context: .
      dockerfile: Recording.Dockerfile
    volumes:
      - recordings:/app/recordings
    devices:
      - /dev/snd:/dev/snd
    environment:
      - RECORDING_LENGTH=15
      - SAMPLE_RATE=48000
      - FILENAME_FORMAT={date}-birdnet-{time}.wav
      - RECS_DIR=/app/recordings
      - MAX_RECORDS=1  # Keep only 10 latest recordings
  analyzer:
    build:
      context: .
      dockerfile: TensorFlow.Dockerfile
    volumes:
      - recordings:/app/recordings
      - processed:/app/processed
    environment:
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
    depends_on:
      - recording

  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - db-data:/app/database  # Database storage  
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5050"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  recordings:
  processed:  
  db-data: