version: '3.8'
services:
  recording:
    build:
      context: .
      dockerfile: Recording.Dockerfile
    volumes:
      - recordings:/app/recordings
    devices:
      - /dev/snd:/dev/snd
    environment:
      - RECORDING_LENGTH=15
      - SAMPLE_RATE=48000
      - FILENAME_FORMAT={date}-birdnet-{time}.wav
      - RECS_DIR=/app/recordings

  tensorflow:
    build:
      context: .
      dockerfile: TensorFlow.Dockerfile
    volumes:
      - recordings:/app/recordings

volumes:
  recordings:  